volumes:
  redis:

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile-flask
    env_file:
      - .env
    expose:
      - "5000"
    ports:
      - 5000:5000
    command: bash -c "/bin/docker-entrypoint.sh"

  solr:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-solr
    restart: always
    environment:
      SOLR_LOG_LEVEL: INFO
      LD_BIND_NOW: 1
    ports:
      - "8983:8983"
    volumes:
      - ./docker/solr:/opt/solr/server/solr/home
      - ./docker/solr-data:/data-solr
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

  solr9:
    image: solr:9
    restart: always
    environment:
      SOLR_LOG_LEVEL: INFO
      LD_BIND_NOW: 1
      SOLR_SECURITY_MANAGER_ENABLED: false
    ports:
      - "8984:8983"
    volumes:
      - ./docker/solr9:/var/solr/data
      - ./docker/solr9-data:/data-solr
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

  redis:
    image: redis:6
    command: redis-server --appendonly yes
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  indexer:
    build:
      context: indexer
      dockerfile: Dockerfile-indexer
    env_file:
      - .env
    command: bash -c "/data/index.sh"
    volumes:
      - ${CSV_FOLDER_IMPORT_PATH}:/data/csv_import_files
