events {}

http {
	server {
		listen 80;
		server_name _;
		return 301 https://$host$request_uri;
	}

	server {
		listen 443 ssl;

		ssl_certificate     /etc/nginx/ssl/ssl.crt;
		ssl_certificate_key /etc/nginx/ssl/ssl.key;

		# Redirect old blog URLs to emlo-portal
		rewrite ^/blog/(.*) http://emlo-portal.bodleian.ox.ac.uk/collections/$1 permanent;                                                                                        

		#rewrite ^/images/(.*) /img/$1 last;

		add_header Content-Security-Policy "upgrade-insecure-requests" always;

		location / {
			proxy_pass http://web:5000;
		}
	}
}
